Traceback (most recent call last):
  File "/home/kafa46/anaconda3/envs/book_writing/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/kafa46/anaconda3/envs/book_writing/lib/python3.7/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/kafa46/anaconda3/envs/book_writing/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/kafa46/anaconda3/envs/book_writing/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/kafa46/anaconda3/envs/book_writing/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/kafa46/anaconda3/envs/book_writing/lib/python3.7/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/kafa46/anaconda3/envs/book_writing/lib/python3.7/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/kafa46/anaconda3/envs/book_writing/lib/python3.7/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# 들여쓰기를 통해 함수의 인자를 표시한 것을 확인할 수 있음
foo = long_function_name(var_one, var_two,
                         var_three, var_four)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_1188927/1621955859.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# 들여쓰기를 통해 함수의 인자를 표시한 것을 확인할 수 있음[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m foo = long_function_name(var_one, var_two,
[0m[1;32m      3[0m                          var_three, var_four)

[0;31mNameError[0m: name 'long_function_name' is not defined
NameError: name 'long_function_name' is not defined

